version: '3.9'
services:
  spring:
    image: 'personapi:2.0.0'
    ports:
      - '8080:8080'
    container_name: spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/personapi
      - SPRING_DATASOURCE_USERNAME=personapi
      - SPRING_DATASOURCE_PASSWORD=personapi
  db:
    image: 'postgres:15.2-bullseye'
    ports:
      - '5432:5432'
    container_name: db
    environment:
      - POSTGRES_USER=personapi
      - POSTGRES_PASSWORD=personapi
    volumes: 
      - dbz:/var/lib/postgresql/data
volumes:
  dbz:
    driver: local
